version: '3.8'

services:
  maildev:
    image: maildev/maildev:latest
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP Server
    environment:
      - MAILDEV_INCOMING_USER=
      - MAILDEV_INCOMING_PASS=
